model_reasoning_effort = "xhigh"
model = "gpt-5.1-codex-max"

notify = ["python3", "/Users/icedac/.codex/script/notify.py"]

[sandbox_workspace_write]
network_access = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
